services:
  api:
    build: .
    platform: linux/amd64
    container_name: cap_server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: >
      sh -c "sleep 15 && uvicorn src.cap.main:app --host 0.0.0.0 --port 8000"
    depends_on:
      virtuoso:
        condition: service_started
      jaeger:
        condition: service_started
      postgres:
        condition: service_healthy
      ollama:
        condition: service_healthy
    networks:
      - app-network

  postgres:
    image: postgres:16
    ports:
      - "5433:5432"   # host access (avoid clashing with any local 5432)
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./ops/sql/init-cap.sql:/docker-entrypoint-initdb.d/10-init-cap.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB:-postgres} -h localhost"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - app-network

  virtuoso:
    image: openlink/virtuoso-opensource-7:latest
    platform: linux/amd64
    container_name: virtuoso
    ports:
      - "8892:8890"   # host access (avoid clashing with any local 8890)
      - "1113:1111"   # host access (avoid clashing with any local 1111)
    env_file:
      - .env
    volumes:
      - /home/marcio/data/cardano/virtuoso:/database
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8890/sparql >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
    networks:
      - app-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    platform: linux/amd64
    container_name: jaeger
    ports:
      - "16688:16686" # UI
      - "4319:4317"   # OTLP gRPC
      - "4322:4318"   # OTLP HTTP
    env_file:
      - .env
    networks:
      - app-network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 30s
    restart: unless-stopped
    networks:
      - app-network

  ollama-setup:
    image: ollama/ollama:latest
    container_name: ollama-setup
    depends_on:
      ollama:
        condition: service_healthy
    entrypoint: /bin/sh
    command: >
      -c "
      echo 'Waiting for Ollama service to be ready...' &&
      sleep 5 &&
      echo 'Pulling mobr/cap model...' &&
      ollama pull mobr/cap &&
      echo 'Model pulled successfully!'
      "
    environment:
      - OLLAMA_HOST=ollama:11434
    networks:
      - app-network

  cardano-node-preview:
    image: ghcr.io/intersectmbo/cardano-node:10.4.0
    platform: linux/amd64
    container_name: cardano-node-preview
    command: >
      run
      --config /config/config.json
      --topology /config/topology.json
      --database-path /data
      --socket-path /data/node.socket
      --host-addr 0.0.0.0
      --port 3001
    ports:
      - "3001:3001"
    volumes:
      - ${HOME}/cardano/preview-config:/config
      - ${PWD}/backend/assets:/assets
      - ${HOME}/cardano/db:/data
    healthcheck:
      test: ["CMD-SHELL", "test -S /data/node.socket"]
      interval: 15s
      timeout: 5s
      retries: 30
    networks:
      - app-network

  dbsetup:
    image: ghcr.io/intersectmbo/cardano-db-sync:13.6.0.2
    platform: linux/amd64
    container_name: cardano-dbsetup
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - app-network
    volumes:
      - ${PWD}/cardano-db-sync/scripts:/scripts:ro
    entrypoint: ["/bin/bash", "-lc"]
    command: ["/scripts/postgresql-setup.sh --createdb"]
    profiles: ["manual"]  # run with: docker compose run --rm dbsetup

networks:
  app-network:
    driver: bridge

volumes:
  virtuoso-data:
  postgres-data:
  ollama-data: